{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set name = pyproject.get('project').get('name') %}
{% set license = pyproject.get('project').get('license').get('text') %}
{% set description = pyproject.get('project').get('description') %}
{% set url = pyproject.get('project').get('urls').get('Homepage') %}
{% set entry_points = pyproject.get('project').get('script', []) %}
{% set requirements = pyproject.get('project').get('dependencies', [])%}
{% set python_require = 
  pyproject.get('project').get('requires-python', '>=3.7')%}

# Get package version with setuptools_scm
{% set version = os.popen('python -c "import setuptools_scm;print(setuptools_scm.get_version())"').read().strip()%}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # Relative path to the parent directory of the recipe.
  path: ..

build:
  noarch: python
  entry_points: {{ entry_points }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_require }}
    - setuptools-scm
  run:
    - python {{ python_require }}
    {% for dep in requirements %}
    - {{ dep.lower() }}
    {% endfor %}
test:
  imports:
    - {{ name }}
  requires:
    - pip
  commands:
    - pip check

about:
  home: {{ url }}
  license: {{ license }}
  summary: {{ description }}



